add ComparingByMembers(Func<Type, bool> predicate) to SelfReferenceEq…
fluentassertions/fluentassertions pull request #1383
Opened 2020-09-10 04:29 UTC by ursenzler

…uivalencyAssertionOptions<TSelf>

## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [ ] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [ ] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

2020-09-11 18:06 UTC, dennisdoomen requested changes
Would you be willing to also update the release notes and documentation as listed in the PR template? Otherwise we have to pick up the PR ourselves.

2020-09-11 18:06 UTC, dennisdoomen commented on Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
> +        public TSelf ComparingByMembers(Func<Type, bool> predicate)
❌ Please document this new member in the same style as the other overloads.

2020-09-11 18:06 UTC, dennisdoomen commented on Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
> +        public void When_defining_comparing_by_members_with_callback_that_returns_false_then_the_normal_equality_strategy_process_should_be_used()
🙃 I'm nitpicking here, but we prefer to keep those test names functional and never refer to the literal name of an identifier, e.g. `When_none_of_the_members_should_be_compared_by_members_it_should_succeed`

2020-09-11 18:06 UTC, dennisdoomen commented on Tests/FluentAssertions.Specs/Equivalency/BasicEquivalencySpecs.cs
> +        public void When_defining_comparing_by_members_with_callback_it_should_use_force_members_strategy_if_a_callback_returning_true_is_found()
🤔 So is there some implicit or explcit order? Would be nice to capture that in a functional test name.

2020-10-09 09:09 UTC, ursenzler commented
I close this PR because the change how `ComparingByMember<object>` handles basic types solves the same problem.

2020-10-09 09:09 UTC, closed without merging