Issue 1160
fluentassertions/fluentassertions pull request #1416
Opened 2020-10-27 20:56 UTC by Serg046

## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [ ] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [ ] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

Issue #1160

2020-10-27 21:04 UTC, Serg046 commented
ThenNotBeInAscendingOrder and ThenNotBeInDescendingOrder are not provided because it will significantly complicate the change. The issue is the following lines of `NotBeOrderedBy`:
```csharp
Execute.Assertion
    .ForCondition(!unordered.SequenceEqual(expectation))
    .BecauseOf(because, becauseArgs)
    .FailWith("Expected {context:collection} {0} to not be ordered {1}{reason} and not result in {2}.",
        Subject, orderString, expectation);
```
It would be much more complex that just `!unordered.SequenceEqual(expectation)`.
Anyway, I don't think it is worth implementing because even if they were implemented, it would be difficult to understand their behavior therefore they would be in rare use.

2020-10-28 06:57 UTC, dennisdoomen requested changes
👍 Nice work. 
❌ Please update the title to be functional

2020-10-28 06:57 UTC, dennisdoomen commented on Src/FluentAssertions/Collections/SubsequentOrderingGenericCollectionAssertions.cs
> +    public class SubsequentOrderingGenericCollectionAssertions<T> :
🔧 Maybe rename it to `SubsequentOrderingAssertions`?

2020-10-28 06:57 UTC, dennisdoomen commented on docs/_pages/releases.md
> +* Added ThenBeInAscendingOrder and ThenBeInDescendingOrder to allow asserting that a subsequence is ordered in ascending or descending order - [#1416](https://github.com/fluentassertions/fluentassert
🙃 Would be nice to format those names using back-ticks.

2020-10-28 06:57 UTC, dennisdoomen commented on Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs
> +        public void When_asserting_subsequence_by_then_be_in_ascending_order_it_should_pass()
🤔 Try to keep the names of test functional and never refer to the literal name of a method or API, e.g.

`When_the_collection_is_ordered_according_to_the_subsequent_ordering_assertion_it_should_succeed`

2020-10-28 07:18 UTC, jnyrup reviewed
Does this support multiple `ThenBeInAscendingOrder`?
E.g.
```cs
collection.Should()
	.BeInAscendingOrder(x => x.Item1)
	.And
	.ThenBeInAscendingOrder(x => x.Item2)
	.And
	.ThenBeInAscendingOrder(x => x.Item3);
```

2020-10-28 07:18 UTC, jnyrup commented on Tests/FluentAssertions.Specs/Collections/GenericCollectionAssertionsSpecs.cs
> +            var collection = new[]
Please use the AAA-syntax.
```
// Arrange
// Act
// Assert
```

2020-10-28 12:22 UTC, Serg046 commented
Applied the notes and added two tests showing multiple `ThenBeInAscending(Descending)Order` support

2020-10-28 14:30 UTC, jnyrup approved these changes

2020-10-28 15:42 UTC, dennisdoomen approved these changes

2020-10-28 15:42 UTC, merged