Add Guid .Be input checking and .NotBe
fluentassertions/fluentassertions pull request #1597
Opened 2021-06-03 15:15 UTC by eNeRGy164

* Added parameter checking to `Be`
* Added `NotBe` for symmetry.

Should close #1553

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [x] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [x] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [x] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

2021-06-03 16:19 UTC, dennisdoomen requested changes

2021-06-03 16:19 UTC, dennisdoomen commented on Src/FluentAssertions/Primitives/GuidAssertions.cs
> +                throw new ArgumentException("Unable to parse value as a valid GUID", nameof(expected));
I think we should include the value of the string in the exception message

2021-06-03 19:50 UTC, dennisdoomen approved these changes

2021-06-03 19:56 UTC, jnyrup requested changes

2021-06-03 19:56 UTC, jnyrup commented on Src/FluentAssertions/Primitives/GuidAssertions.cs
> +            return Be(unexpectedGuid, because, becauseArgs);
Be -> NotBe

2021-06-03 20:49 UTC, eNeRGy164 commented on Src/FluentAssertions/Primitives/GuidAssertions.cs
> +            return Be(unexpectedGuid, because, becauseArgs);
I'm ashamed

2021-06-04 04:33 UTC, jnyrup approved these changes

2021-06-04 04:33 UTC, merged