Add test for guard helper class
fluentassertions/fluentassertions pull request #1871
Opened 2022-03-31 12:33 UTC by ITaluone

This ref. #1823 

I don't know if these tests are important, but in case they are.. 

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

2022-03-31 15:21 UTC, jnyrup requested changes
Besides the single comment I'm good with this.

2022-03-31 15:21 UTC, jnyrup commented on Src/FluentAssertions/Common/Guard.cs
> +            ThrowIfArgumentIsNull(obj, paramName, string.Empty);
Are you aware that this changes behavior?
I think the former, i.e. keeping it as it is, is better.
![image](https://user-images.githubusercontent.com/919634/161090048-f00aafeb-50af-4e7b-bcdf-f4ee3bacd854.png)

Also applies to the change to `ThrowIfArgumentIsNullOrEmpty`.

2022-04-01 06:21 UTC, ITaluone commented
I don't know how to arrange a test for `ThrowIfArgumentIsOutOfRange`.. Because `T` is an `enum`

2022-04-01 08:29 UTC, eNeRGy164 commented
> I don't know how to arrange a test for `ThrowIfArgumentIsOutOfRange`.. Because `T` is an `enum`

Cast any enum to a value that's not listed. For example `(CSharpAccessModifier)1000`

2022-04-01 08:32 UTC, ITaluone commented
ahh.. thank you :)

2022-04-01 14:28 UTC, dennisdoomen commented
To be honest, I see no value in those extra tests. This is internal code that is already covered by all other code and only exists because of that other code. In fact, `ThrowIfArgumentContainsNull` can even be removed since it is dead code anyway.

2022-04-01 14:48 UTC, IT-VBFK commented
Ok, removing dead code counts as "improve code coverage" IMO :)

2022-04-01 15:10 UTC, dennisdoomen commented
There's an overload.

2022-04-01 18:53 UTC, IT-VBFK commented
How I can see the code coverage on coveralls for the latest CI build?

2022-04-01 18:56 UTC, jnyrup commented
I've _just_ started the CI pipeline.
Once it's done in ~10min the Coveralls bot will post a comment in this PR with a summary of the results.
To view the individual files you'll have to login to Coveralls with your GitHub account.

2022-04-01 19:03 UTC, jnyrup commented
And if you can't wait for the bot to post, here are the change for `Guard.cs`
https://coveralls.io/builds/47932197/source?filename=Src%2FFluentAssertions%2FCommon%2FGuard.cs

2022-04-01 19:07 UTC, jnyrup commented
Instead of adding tests of `ThrowIfArgumentContainsNull<T>(IEnumerable<T> values, string paramName, string message)` we could delete it, as it is dead code.

According to https://coveralls.io/builds/47932179/source?filename=Src%2FFluentAssertions%2FCommon%2FGuard.cs#L58
all the other lines are already covered by other tests.

2022-04-02 07:48 UTC, dennisdoomen commented
> Instead of adding tests of `ThrowIfArgumentContainsNull<T>(IEnumerable<T> values, string paramName, string message)` we could delete it, as it is dead code.

That's exactly what I said ;-)

However, I don't get why Coverall did not post an update here. @eNeRGy164 any idea why it sometimes works and sometimes doesn't?

2022-04-02 12:33 UTC, IT-VBFK commented
> There's an overload.

Here is an example of what I have thought about to be able to remove `ThrowIfArgumentContainsNull<T>()`.

This applies to all four assertions..

```csharp

public MethodInfoSelector(IEnumerable<Type> types)
{
    types.ToList()
        .ForEach(type => Guard.ThrowIfArgumentIsNull(type, nameof(type)));
    Guard.ThrowIfArgumentIsNull(types, nameof(types));

    selectedMethods = types.SelectMany(t => t
        .GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
        .Where(method => !HasSpecialName(method)));
}

```

because removing the overload would be a breaking change IMO

2022-04-02 13:04 UTC, jnyrup commented
It's non-breaking to remove any unused members of `Guard` since the class is `internal`.

So `public static void ThrowIfArgumentContainsNull<T>(IEnumerable<T> values, string paramName)` should be kept as it is used.

`public static void ThrowIfArgumentContainsNull<T>(IEnumerable<T> values, string paramName, string message)` can be removed as it unused and not public because `Guard` is `internal`.

2022-04-02 17:28 UTC, dennisdoomen commented
Maybe you're using an IDE that doesn't allow you to find usages, but my IDE (Rider) clearly tells me that the overload of `ThrowIfArgumentContainsNull` that takes three parameters isn't used at all. 

![image](https://user-images.githubusercontent.com/572734/161383737-30153f7b-a28d-4b22-8782-1dd5e698f853.png)

2022-04-04 06:38 UTC, ITaluone commented
ok, that was completely my fault 🙈 

I have written the tests and therefore it showes up "2 usages".. (the tests)

I should have checked that before writing the tests :D

2022-04-04 09:11 UTC, eNeRGy164 commented
> However, I don't get why Coverall did not post an update here. @eNeRGy164 any idea why it sometimes works and sometimes doesn't?

At first, there was no run CI initiated by default because it's @ITaluone's first contribution.
But why there was no post after the actual run, I also don't know. I can only guess that maybe the API between Coveralls and GitHub is overloaded or something like that. Can't see anything specific.

2022-04-04 17:38 UTC, dennisdoomen commented
> I should have checked that before writing the tests :D

Those tests can be removed anyway.

2022-04-05 05:31 UTC, ITaluone commented
ok, got it

2022-04-05 05:58 UTC, jnyrup approved these changes

2022-04-05 10:41 UTC, merged