Code style fixes
fluentassertions/fluentassertions pull request #1881
Opened 2022-04-06 09:48 UTC by ITaluone

This PR solves some Visual Studio errors

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

2022-04-06 14:37 UTC, jnyrup requested changes

2022-04-06 14:37 UTC, jnyrup commented on Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
> +            new Config();
Have a look at the changes in 684b5782b79d0f50094e61451dc77eaa5bc27647

`IEquivalencyAssertionOptions` is now a member of `IEquivalencyValidationContext`.
So I would just make `Context.Options` writable and initialize it as
```cs
context = new Context()
{
    Options = new Config()
};
```

2022-04-06 15:02 UTC, ITaluone commented
Or initialize it like: `public IEquivalencyAssertionOptions Options { get; } = new Config();` ?

2022-04-06 15:06 UTC, jnyrup commented
> Or initialize it like: `public IEquivalencyAssertionOptions Options { get; } = new Config();` ?

No need to spend more energy on this class.
These benchmarks are not run in any automatic way.

2022-04-07 05:17 UTC, ITaluone commented
Just realized there were changes in wrong commits :)

2022-04-07 08:10 UTC, merged