Fix coveralls badge
fluentassertions/fluentassertions pull request #1906
Opened 2022-04-20 06:16 UTC by ITaluone

## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

Since the coveralls badge is not rendering correctly, I remove the optional parameter from the badge link. Seems to fix this issue..

2022-04-21 19:15 UTC, jnyrup commented
The badge renders fine for me?

2022-04-22 04:34 UTC, ITaluone commented
Hmm.. weird now it does it fine for me too 🤔

Maybe this was a caching problem..

2022-04-22 06:54 UTC, jnyrup commented
Could be a combination of caching and the problems Coveralls had the other day: https://status.coveralls.io/

2022-04-23 10:11 UTC, jnyrup requested changes
I'm fine switching to displaying the numbers for master.
As _developers_ on FA we can see the current numbers by going to [coveralls](https://coveralls.io/github/fluentassertions/fluentassertions).
For _consumers_ of FA I guess it's more "correct" to show the numbers for the published nuget package.

2022-04-23 10:11 UTC, jnyrup commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/fluentassertions/fluentassertions/badge.svg)](https://coveralls.io/github/fluentassertions/fluentassertions)
By default coveralls picks the default git branch which is `develop`.

```suggestion
[![Coverage Status](https://coveralls.io/repos/github/fluentassertions/fluentassertions/badge.svg?branch=master)](https://coveralls.io/github/fluentassertions/fluentassertions?branch=master)
```

2022-04-25 03:57 UTC, jnyrup approved these changes

2022-04-25 05:17 UTC, merged