closes #2008
fluentassertions/fluentassertions pull request #2010
Opened 2022-10-11 10:40 UTC by A-Kjeldgaard

Changed the private field to a public property, thereby exposing the IMonitor object to extensions methods.

- Added Unit test.
- Ran and updated accept api changes.
- Added release notes.

2022-10-13 10:08 UTC, dennisdoomen requested changes
Thanks. Only minor comments.

2022-10-13 10:08 UTC, dennisdoomen commented on Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
> +        public void Event_Assertions_should_expose_monitor()
🔧 Please keep names functional, so `Event_assertions_should_expose_the_monitor`

2022-10-13 18:24 UTC, jnyrup approved these changes
I've got nothing extra to add. 
Always happy to improve the extensibility.

2022-10-14 12:06 UTC, A-Kjeldgaard commented
Requested changes hereby fixed 👍

2022-10-14 14:59 UTC, dennisdoomen approved these changes

2022-10-14 15:11 UTC, merged