Add `ThatAre[Not]Sealed` to `TypeSelecot.cs` as mentioned in Issue 645
fluentassertions/fluentassertions pull request #2059
Opened 2022-12-05 10:52 UTC by 94sedighi

## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

2022-12-18 08:30 UTC, dennisdoomen requested changes

2022-12-18 08:30 UTC, dennisdoomen commented on Src/FluentAssertions/Types/TypeSelector.cs
> +    /// Determines wether the type is sealed
🔧 It doesn't determine where a type is sealed, but returns the types that are sealed.

2022-12-18 08:30 UTC, dennisdoomen commented on Src/FluentAssertions/Types/TypeSelector.cs
> +    /// Determines wheter the type is not sealed
🔧 Same comment as the other one.

2022-12-19 09:17 UTC, dennisdoomen approved these changes

2022-12-19 09:18 UTC, dennisdoomen commented
Needs a rebase

2022-12-19 10:23 UTC, jnyrup approved these changes

2022-12-19 10:34 UTC, 94sedighi commented
> Needs a rebase
working on int

2022-12-19 13:00 UTC, merged