Failing event accessors
fluentassertions/fluentassertions pull request #2629
Opened 2024-04-22 13:17 UTC by ITaluone

This finishes #1954 

Closes #1948 

**Note:** All credits goes to @apazureck!

## IMPORTANT 

* [x] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [x] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [x] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [x] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

2024-05-10 17:55 UTC, dennisdoomen requested changes
Thanks for taking over the work. Just some minor comments to address.

2024-05-10 17:55 UTC, dennisdoomen commented on Src/FluentAssertions/Events/EventMonitorOptions.cs
> +    public EventMonitorOptions IgnoreEventAccessorExceptions()
🔧 Similar to `SelfReferenceEquivalencyOptions`, we should `IgnoringEventAccessorExceptions`. Same for `RecordEventsWithBrokenAccessor`

2024-05-10 17:55 UTC, dennisdoomen commented on Src/FluentAssertions/Events/EventMonitorOptions.cs
> +    /// <returns>The options instance for method stacking.</returns>
🔧 No need to explicitly document the return type of a fluent API

2024-05-10 17:55 UTC, dennisdoomen commented on docs/_pages/releases.md
> +* Added options to `.Monitor(...)` extension - [#1954](https://github.com/fluentassertions/fluentassertions/pull/1954)
🔧 We can remove this one as it has no functional purpose. It's only there to support the `IgnoreEventAccessorExceptions` and `RecordEventsWithBrokenAccessor` methods

2024-05-11 07:57 UTC, dennisdoomen approved these changes

2024-05-15 14:05 UTC, jnyrup commented on Src/FluentAssertions/AssertionExtensions.cs
> +    /// <exception cref="ArgumentNullException">Thrown if <paramref name="eventSource"/> is Null.</exception>
```suggestion
    /// <exception cref="ArgumentNullException"><paramref name="eventSource"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentNullException"><paramref name="configureOptions"/> is <see langword="null"/>.</exception>
```

2024-05-15 16:10 UTC, jnyrup commented on docs/_pages/releases.md
> +* Removed `utcNow` overload for `.Monitor<T>()` - [#1954](https://github.com/fluentassertions/fluentassertions/pull/1954)
```suggestion
* Removed `utcNow` overload for `.Monitor<T>()` - [#2629](https://github.com/fluentassertions/fluentassertions/pull/2629)
```

2024-05-15 16:14 UTC, ITaluone commented on docs/_pages/releases.md
> +* Removed `utcNow` overload for `.Monitor<T>()` - [#1954](https://github.com/fluentassertions/fluentassertions/pull/1954)
Ou.. thanks for head up 👍

2024-05-15 16:18 UTC, jnyrup approved these changes

2024-05-15 16:18 UTC, ITaluone commented
wait a sec

2024-05-15 16:22 UTC, ITaluone commented
had a litte incident with rebase/force pushing 🤦‍♂️

2024-05-15 16:34 UTC, merged